version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - ctjhoa
  ignore:
  - dependency-name: ember-cli
    versions:
    - ">= 0"
  - dependency-name: ember-cli-addon-docs*
    versions:
    - ">= 0"
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: eslint-plugin-ember
    versions:
    - 10.1.2
    - 10.2.0
    - 10.3.0
  - dependency-name: ember-template-lint
    versions:
    - 2.17.0
    - 2.18.0
    - 2.18.1
    - 2.19.0
    - 2.21.0
    - 3.1.1
  - dependency-name: "@glimmer/tracking"
    versions:
    - 1.0.3
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
