---
language: node_js
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "10"

dist: xenial

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

branches:
  only:
    - master
    # npm version tags
    - /^v\d+\.\d+\.\d+/

jobs:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

  include:
    # runs linting and tests with current locked deps
    - stage: "Tests"
      name: "Tests"
      script:
        - npm run lint
        - npm run test:ember

    - stage: "Additional Tests"
      name: "Floating Dependencies"
      install:
        - npm install --no-package-lock
      script:
        - npm run test:ember

    # we recommend new addons test the current and previous LTS
    # as well as latest stable release (bonus points to beta/canary)
    - env: EMBER_TRY_SCENARIO=ember-lts-3.16
    - env: EMBER_TRY_SCENARIO=ember-lts-3.20
    - env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=ember-default-with-jquery
    - env: EMBER_TRY_SCENARIO=ember-classic
    #- env: EMBER_TRY_SCENARIO=embroider-safe
    #- env: EMBER_TRY_SCENARIO=embroider-optimized

    - stage: deploy
      if: (branch = master OR tag IS present) AND type = push
      env: NAME=deploy
      script: node_modules/.bin/ember deploy production

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO

deploy:
  provider: npm
  email: npmjs@concordnow.com
  api_key:
    secure: ZZbykO2+YssQ/TV3qc/J4Ejeln3Ug68v+vsSkm91SomIgJkIBJZPWnnnyWjcT2qVrmcxPc+NH69DGqg5IUUeK4ix5m8DmSq4pW2cncqM0K4NHEFFQ1wi4bDfrUZctGEMGhT0OPPnLVumA0Myf0HWEPM3J1Rdk/rhPfmROKM1tmKwNrQ+GJqdQh3G/f/MJfLl/P4w5/xhCyYqxPOiLQvcHbYuhbk+1R/JnIdaWwdfg61AQ44OHX0dTLtqiR+7ZLzRAuD9qIK0ptYJltJWDDR4dEf5oSHGzNYMY0F2V6/bEMNY3IlgTkMhFd+Axy36TpS9Q31AR8hmXeAIkubc7ujiQA2xLqfP+hlNwO0tEWH+i4rmMJarY/soU11qf/8S+EU0ctcKsmxeGoEHmw3Dj8xh2upPMNHDZPF+PyQBHRU5ZTFrE7Mts9pfwrqwpYsUYbpK9DTFHm/oSt4dHZqdbSus5v3QMeQIJV20aTJZldSnBQFNBM39a5Oc+LvXFi0PQX4hus8iWAwvyVs+uEgRsz2T6eSD1p3cQIA5ceRdpAIlINlIyu8/rq1pPaAOHRdQqJr5W778/JVrVsOzIVqI4PVP4TdeUVkKxk8ZSfdhdExcyB0kloAsJ+q7P24FRQaZuGyYmp1h4lwsZxo8zbh9GNtYx4360VjYbcsuqeivTlyrbyw=
  on:
    tags: true
    repo: concordnow/ember-aria-tabs
